[theme]
base="dark"
primaryColor="#6366F1"
backgroundColor="#050816"
secondaryBackgroundColor="#020617"
textColor="#E5E7EB"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
